-- PAN Details Table
CREATE TABLE IF NOT EXISTS pan_details (
    pan_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT UNIQUE NOT NULL,
    pan_number VARCHAR(10) UNIQUE NOT NULL,
    pan_name VARCHAR(255),
    pan_front VARCHAR(500),
    verification VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_pan_details_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- Aadhaar Details Table
CREATE TABLE IF NOT EXISTS aadhaar_details (
    aadhaar_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT UNIQUE NOT NULL,
    aadhaar_number VARCHAR(12) UNIQUE NOT NULL,
    aadhaar_front VARCHAR(500),
    aadhaar_back VARCHAR(500),
    verification VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_aadhaar_details_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- Signature Details Table
CREATE TABLE IF NOT EXISTS signature_details (
    signature_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT UNIQUE NOT NULL,
    signature_image VARCHAR(500),
    verification VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_signature_details_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- Bank Accounts Table
CREATE TABLE IF NOT EXISTS bank_accounts (
    bank_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT UNIQUE NOT NULL,
    bank_name VARCHAR(255),
    account_number VARCHAR(50) UNIQUE NOT NULL,
    ifsc_code VARCHAR(20) NOT NULL,
    account_holder VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_bank_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);