CREATE TABLE IF NOT EXISTS kyc (
    kyc_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT UNIQUE NOT NULL,
    pan_id BIGINT UNIQUE,
    aadhaar_id BIGINT UNIQUE,
    signature_id BIGINT UNIQUE,
    bank_id BIGINT UNIQUE,
    kyc_status VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED',
    submitted_at TIMESTAMP,
    approved_at TIMESTAMP,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_kyc_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_kyc_pan
        FOREIGN KEY (pan_id)
        REFERENCES pan_details(pan_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_kyc_aadhaar
        FOREIGN KEY (aadhaar_id)
        REFERENCES aadhaar_details(aadhaar_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_kyc_signature
        FOREIGN KEY (signature_id)
        REFERENCES signature_details(signature_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_kyc_bank
        FOREIGN KEY (bank_id)
        REFERENCES bank_accounts(bank_id)
        ON DELETE SET NULL
);