ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS last_price NUMERIC(12,2);

ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS day_high NUMERIC(12,2);

ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS day_low NUMERIC(12,2);

ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS market_open NUMERIC(12,2);

ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS previous_close NUMERIC(12,2);

ALTER TABLE stocks
ADD COLUMN IF NOT EXISTS price_updated_at TIMESTAMP;
